package com.junbingao.remotecontrol.core.state

/**
 * The core's own words in Chinese: every key RCCore looks up through `L10n`, with the zh-Hans
 * value `ios/App/Localizable.xcstrings` gives it. A key is its own English, so English needs no
 * table, and a key missing here reads as English, as a missing catalogue entry does on the iPhone.
 * `LocalizationTests` holds every entry to the iPhone catalogue's.
 */
internal object Localizable {
    val zhHans: Map<String, String> = mapOf(
        "%.1fs" to "%.1f 秒",
        "%@ API key" to "%@ API 密钥",
        "%@ account" to "%@ 账户",
        "%@ is larger than 6 MB. Attach a smaller file." to "%@ 超过 6 MB，请换一个更小的文件。",
        "%@ · %lld waiting" to "%@ · %lld 个等待",
        "%@, effort %@" to "%@，思考强度 %@",
        "%lld device" to "%lld 台设备",
        "%lld devices" to "%lld 台设备",
        "%lld message" to "%lld 条消息",
        "%lld messages" to "%lld 条消息",
        "%lld%%" to "%lld%%",
        "%lld-day" to "%lld 天",
        "%lld-hour" to "%lld 小时",
        "%lld-minute" to "%lld 分钟",
        "%lldd" to "%lld 天前",
        "%lldh" to "%lld 小时前",
        "%lldm" to "%lld 分钟前",
        "%lldm %llds" to "%lld 分 %lld 秒",
        "%llds" to "%lld 秒",
        "A folder with that name already exists." to "已存在同名文件夹。",
        "API key" to "API 密钥",
        "Account" to "账户",
        "Active" to "正常",
        "Admin" to "管理员",
        "Another app took over this connection." to "另一个应用接管了此连接。",
        "Attach at most %lld files to one message." to "一条消息最多附加 %lld 个文件。",
        "Audio is streamed to your gateway, which recognises the language itself." to "音频会传到你的网关转写，并自动识别语言。",
        "Audio stays on this device. Needs an on-device model for the language you pick." to "音频留在本机。需要所选语言的本地模型。",
        "Connected" to "已连接",
        "Connecting" to "连接中",
        "Controlled by the terminal" to "由终端控制",
        "Controlled by the terminal · take over to send" to "由终端控制 · 接管后可发送",
        "Could not reach the keychain. Unlock this device and try again." to "无法访问钥匙串。请解锁设备后重试。",
        "Delivery unconfirmed · retry or dismiss first" to "未确认送达 · 请先重试或忽略",
        "Delivery unconfirmed. Check the session before sending again." to "未确认送达。再次发送前请先查看会话。",
        "Detailed" to "详细",
        "Detailed adds thinking, tool calls and the task list." to "详细会加上思考过程、工具调用和任务列表。",
        "Detect installed agents" to "检测已安装的 agent",
        "Device handshake" to "设备握手",
        "Device offline" to "设备离线",
        "Device online" to "设备在线",
        "Disabled" to "已停用",
        "Disconnected" to "已断开",
        "Down arrow" to "下箭头",
        "Ended at the usage limit" to "在用量限制处结束",
        "Ended at the usage limit · resets %@" to "在用量限制处结束 · %@ 重置",
        "Enter a username and a password." to "请输入用户名和密码。",
        "Enter the full gateway address, for example https://rc.example.com." to "请输入完整的网关地址，例如 https://rc.example.com。",
        "Error" to "出错",
        "For you" to "等你处理",
        "Gateway" to "网关",
        "Gateway ready" to "网关就绪",
        "Hyphen" to "连字符",
        "Left arrow" to "左箭头",
        "Member" to "成员",
        "Model" to "模型",
        "Moderate" to "适中",
        "Not connected to the gateway." to "未连接到网关。",
        "Not resumed" to "未继续",
        "Not running" to "未运行",
        "Not signed in" to "未登录",
        "Offline" to "离线",
        "Offline · your draft is saved" to "离线 · 草稿已保存",
        "On this iPhone" to "在本机",
        "Paste" to "粘贴",
        "Paused by the usage limit · resumes %@" to "已被用量限制暂停 · %@ 继续",
        "Paused by the usage limit · resumes about %@" to "已被用量限制暂停 · 约 %@ 继续",
        "Permissions" to "权限",
        "Pick a time between a minute from now and eight days away." to "请选择一分钟之后、八天之内的时间。",
        "Pipe" to "竖线",
        "Polishing…" to "润色中…",
        "Queue" to "排队",
        "Refused" to "已拒绝",
        "Registration is closed." to "注册未开放。",
        "Remote Control %@ · Gateway %@ · Protocol v%lld" to "Remote Control %@ · 网关 %@ · 协议 v%lld",
        "Remote Control %@ · Protocol v%lld" to "Remote Control %@ · 协议 v%lld",
        "Resume cancelled" to "已取消继续",
        "Resume moved" to "继续时间已更改",
        "Resume moved to %@" to "继续时间已改为 %@",
        "Resume moved to about %@" to "继续时间已改为约 %@",
        "Resume scheduled" to "已安排继续",
        "Resume scheduled for %@" to "已安排在 %@ 继续",
        "Resume scheduled for about %@" to "已安排在约 %@ 继续",
        "Right arrow" to "右箭头",
        "Send" to "发送",
        "Sent for you after the limit reset" to "限制重置后代你发送",
        "Shell exited" to "Shell 已退出",
        "Shell exited (%lld)" to "Shell 已退出（%lld）",
        "Simple" to "简约",
        "Simple shows only what is written to you." to "简约只显示写给你看的内容。",
        "Slash" to "斜杠",
        "Strong" to "较强",
        "That account no longer exists." to "该账户已不存在。",
        "That device is offline" to "该设备离线",
        "That device or session no longer exists." to "该设备或会话已不存在。",
        "That is more than 64 KB of text. Paste less of it." to "文本超过 64 KB。请少粘贴一些。",
        "That is not your current password." to "当前密码不正确。",
        "That message has already been sent." to "这条消息已经发出。",
        "That message is longer than 64 KB. Shorten it or attach a file." to "消息超过 64 KB。请缩短内容，或改为附加文件。",
        "That response was too large to load." to "响应内容过大，无法加载。",
        "That username is taken." to "该用户名已被占用。",
        "The gateway did not answer in time." to "网关未在规定时间内响应。",
        "The gateway did not return a transcript." to "网关没有返回转写结果。",
        "The gateway does not have this feature enabled." to "网关未启用此功能。",
        "The gateway refused this request." to "网关拒绝了此请求。",
        "The gateway request failed (%lld)." to "网关请求失败（%lld）。",
        "The gateway sent a frame this app could not read (%@)." to "网关发来的帧本应用无法解析（%@）。",
        "The gateway sent a response this app could not read." to "网关发来的响应本应用无法解析。",
        "The transcript did not finish. What was recognised is in your draft." to "转写未完成。已识别的内容保留在草稿中。",
        "The transcription connection dropped." to "转写连接已断开。",
        "This account cannot be changed." to "该账户不能被修改。",
        "This account is disabled." to "该账户已被停用。",
        "This app speaks protocol %lld; the gateway speaks %lld. Update both sides." to "本应用使用协议 %lld，网关使用 %lld。请同时更新两端。",
        "This device already runs four terminals. Close one first." to "此设备已运行四个终端。请先关闭一个。",
        "This device does not offer a terminal." to "此设备不提供终端。",
        "This device is offline." to "此设备当前离线。",
        "This gateway refused the connection. Ask whoever runs it for access." to "此网关拒绝了连接。请向网关管理者申请访问权限。",
        "Tilde" to "波浪号",
        "Too many attempts. Wait a moment and try again." to "尝试次数过多。请稍候再试。",
        "Up arrow" to "上箭头",
        "Usernames are 3 to 32 characters: lower-case letters, digits, dots, underscores and hyphens. Passwords are 8 characters or more." to "用户名为 3 到 32 个字符：小写字母、数字、点、下划线和连字符。密码至少 8 个字符。",
        "Waiting for your answer" to "等待你的回答",
        "When Claude Code or Codex stops at a usage limit, the device continues the session a minute after the limit resets." to "当 Claude Code 或 Codex 因用量限制停下时，设备会在限制重置一分钟后继续该会话。",
        "Working" to "运行中",
        "Working · %lld message queued" to "正在工作 · %lld 条消息排队",
        "Working · %lld messages queued" to "正在工作 · %lld 条消息排队",
        "Working · your message will be queued" to "正在工作 · 消息将排队",
        "Working · your message will steer the turn" to "正在工作 · 消息将转向当前任务",
        "Wrong username or password." to "用户名或密码错误。",
        "Your gateway does not offer this yet." to "你的网关还不支持这项设置。",
        "Your session expired. Sign in again." to "登录已过期，请重新登录。",
        "never" to "从未",
        "now" to "刚刚",
        "offline" to "离线",
        "online" to "在线",
        "resets %@" to "%@ 重置",
        "second try" to "第二次尝试",
        "third try" to "第三次尝试",
        "yesterday" to "昨天",
    )
}
