"""Amendment A32: Claude rows that carry the user role but nobody's words.

The rows below are the shapes Claude Code 2.1.271 really writes, copied from a
transcript on a developer machine and emptied of anything private.
"""

from __future__ import annotations

from typing import Any

from claude_agent_sdk import SystemMessage, UserMessage

from rc_client.agents.base import COMPACTION_NOTICE
from rc_client.agents.claude import markers
from rc_client.agents.claude.transcripts import TranscriptTailer
from rc_client.agents.claude.translate import ClaudeTranslator

SUMMARY_TEXT = (
    "This session is being continued from a previous conversation that ran out "
    "of context. The summary below covers the earlier portion of the "
    "conversation.\n\nSummary:\n1. Primary Request and Intent: ..."
)
CAVEAT_TEXT = (
    "<local-command-caveat>Caveat: The messages below were generated by the "
    "user while running local commands. DO NOT respond to these messages or "
    "otherwise consider them in your response.</local-command-caveat>"
)
STDOUT_TEXT = (
    "<local-command-stdout>\x1b[2mCompacted (ctrl+o to see full summary)\x1b[22m"
    "</local-command-stdout>"
)
INTERRUPTED = "[Request interrupted by user]"
INTERRUPTED_TOOL = "[Request interrupted by user for tool use]"


def row(text: str, uuid: str, **extra: Any) -> dict[str, Any]:
    """A user row as the CLI writes it, with the fields a mirror reads."""
    return {
        "type": "user",
        "uuid": uuid,
        "cwd": "/repo",
        "sessionId": "sess-1",
        "userType": "external",
        "version": "2.1.271",
        "message": {"role": "user", "content": text},
        **extra,
    }


def command_row(name: str, args: str = "", uuid: str = "row-command") -> dict[str, Any]:
    """What the CLI files when a slash command is typed at the terminal."""
    text = (
        f"<command-name>{name}</command-name>\n"
        f"            <command-message>{name.lstrip('/')}</command-message>\n"
        f"            <command-args>{args}</command-args>"
    )
    return row(text, uuid)


def boundary_row() -> dict[str, Any]:
    """The `system` row that marks where the context was compacted."""
    return {
        "type": "system",
        "uuid": "row-boundary",
        "subtype": "compact_boundary",
        "content": "Conversation compacted",
        "level": "info",
        "logicalParentUuid": "row-compact",
        "compactMetadata": {"trigger": "manual", "preTokens": 729299, "postTokens": 13304},
        "cwd": "/repo",
        "sessionId": "sess-1",
    }


def tailer() -> TranscriptTailer:
    return TranscriptTailer(path="/nonexistent", cwd="/repo")


def kinds(emits: list[Any]) -> list[str]:
    return [emit.kind for emit in emits]


# ---------------------------------------------------------------- the markers


def test_the_summary_row_is_recognised_by_the_flag_the_cli_sets() -> None:
    assert markers.is_compaction_summary(row(SUMMARY_TEXT, "s", isCompactSummary=True)) is True
    assert markers.is_compaction_summary(row("please fix the test", "t")) is False


def test_both_interruption_markers_are_recognised_and_nothing_else_is() -> None:
    assert markers.is_interruption(INTERRUPTED) is True
    assert markers.is_interruption(f"\n{INTERRUPTED_TOOL}\n") is True
    assert markers.is_interruption("Request interrupted by user, sorry") is False


def test_the_reply_to_a_command_is_output_but_the_caveat_is_not() -> None:
    assert markers.is_command_output(STDOUT_TEXT) is True
    assert markers.is_command_output(CAVEAT_TEXT) is False


def test_a_typed_command_reads_back_as_the_terminal_shows_it() -> None:
    text = command_row("/model", "haiku")["message"]["content"]
    assert markers.typed_command(text) == "/model haiku"
    assert markers.typed_command(command_row("/compact")["message"]["content"]) == "/compact"
    assert markers.typed_command("write /model in the doc") is None


# ------------------------------------------------------------- the transcript


def test_the_compaction_summary_is_no_block_and_changes_no_turn() -> None:
    reader = tailer()
    assert reader.translate(row(SUMMARY_TEXT, "row-summary", isCompactSummary=True)) == []
    assert reader.busy is False
    reader.translate(row("go", "row-prompt"))
    assert reader.translate(row(SUMMARY_TEXT, "row-summary-2", isCompactSummary=True)) == []
    assert reader.busy is True


def test_the_boundary_row_is_the_line_the_apps_hear_about_a_compaction() -> None:
    emits = tailer().translate(boundary_row())
    assert kinds(emits) == ["notice"]
    assert emits[0].fields == {"level": "info", "text": COMPACTION_NOTICE}


def test_an_interruption_marker_ends_the_turn_and_opens_no_bubble() -> None:
    reader = tailer()
    reader.translate(row("go", "row-prompt"))
    busy = [reader.busy]
    assert reader.translate(row(INTERRUPTED, "row-stop", interruptedMessageId="msg_1")) == []
    busy.append(reader.busy)
    assert busy == [True, False]
    assert reader.stop_reason == "interrupted"


def test_a_tool_result_in_the_interrupted_row_is_still_published() -> None:
    reader = tailer()
    reader.translate(row("go", "row-prompt"))
    stopped = {
        "type": "user",
        "uuid": "row-stop-tool",
        "message": {
            "role": "user",
            "content": [
                {"type": "tool_result", "tool_use_id": "toolu_1", "content": "partial"},
                {"type": "text", "text": INTERRUPTED_TOOL},
            ],
        },
    }
    emits = reader.translate(stopped)
    assert kinds(emits) == ["tool_call"]
    assert emits[0].fields["output"] == "partial"
    assert reader.stop_reason == "interrupted"


def test_the_next_turn_clears_the_interruption() -> None:
    reader = tailer()
    reader.translate(row("go", "row-prompt"))
    reader.translate(row(INTERRUPTED, "row-stop"))
    reader.translate(row("carry on", "row-prompt-2"))
    assert reader.busy is True
    assert reader.stop_reason == "completed"


def test_a_typed_command_is_the_persons_words_and_starts_no_turn() -> None:
    reader = tailer()
    emits = reader.translate(command_row("/model", "haiku"))
    assert kinds(emits) == ["user_message"]
    assert emits[0].fields == {
        "block_id": "row-command",
        "text": "/model haiku",
        "source": "terminal",
    }
    assert reader.busy is False


def test_the_two_records_the_cli_keeps_of_one_compact_make_one_bubble() -> None:
    reader = tailer()
    typed = reader.translate(row("/compact", "row-compact"))
    assert [emit.fields["text"] for emit in typed] == ["/compact"]
    assert reader.translate(row(CAVEAT_TEXT, "row-caveat", isMeta=True)) == []
    assert reader.translate(command_row("/compact", uuid="row-compact-tag")) == []


def test_a_command_typed_twice_in_a_row_is_published_each_time() -> None:
    reader = tailer()
    first = reader.translate(command_row("/limit-reset", uuid="row-first"))
    reader.translate(row(STDOUT_TEXT, "row-stdout"))
    second = reader.translate(command_row("/limit-reset", uuid="row-second"))
    assert [emit.fields["block_id"] for emit in first + second] == ["row-first", "row-second"]


def test_the_reply_to_a_command_ends_the_turn_it_left_running() -> None:
    reader = tailer()
    reader.translate(row("/compact", "row-compact"))
    busy = [reader.busy]
    assert reader.translate(row(STDOUT_TEXT, "row-stdout")) == []
    busy.append(reader.busy)
    assert busy == [True, False]
    assert reader.stop_reason == "completed"


def test_the_tags_a_command_leaves_behind_stay_out_of_the_timeline() -> None:
    reader = tailer()
    assert reader.translate(row(CAVEAT_TEXT, "row-caveat", isMeta=True)) == []
    assert reader.translate(row("<command-message>compact</command-message>", "row-msg")) == []
    assert reader.translate(row("<command-args></command-args>", "row-args")) == []
    assert reader.busy is False


# --------------------------------------------------------------------- the SDK


def test_a_driven_session_hears_the_same_line_for_a_compaction() -> None:
    translator = ClaudeTranslator(cwd="/repo")
    message = SystemMessage(
        subtype="compact_boundary",
        data={"compact_metadata": {"trigger": "auto", "pre_tokens": 729299}},
    )
    emits = translator.feed(message)
    assert kinds(emits) == ["notice"]
    assert emits[0].fields == {"level": "info", "text": COMPACTION_NOTICE}


def test_a_driven_session_publishes_no_block_for_the_summary() -> None:
    translator = ClaudeTranslator(cwd="/repo")
    assert translator.feed(UserMessage(content=SUMMARY_TEXT, uuid="sdk-summary")) == []
