// Ported from web/src/strings.ts and web/src/strings.zh-Hans.ts. Keep the two
// tables of this file in step with the web's: the English is the source, and
// the Chinese is the web's own translation, copied rather than re-translated.

package com.junbingao.remotecontrol.win.strings

import com.junbingao.remotecontrol.core.state.InterfaceLanguage

/** The `chat` group of the web's string table. */
class ChatStrings(
    val newSession: String,
    val searchPlaceholder: String,
    val sidebarFooter: (Int, Int) -> String,
    val todos: (Int, Int) -> String,
    val todosTitle: String,
    val stop: String,
    val stopping: String,
    val takeOver: String,
    val backToLatest: String,
    val newUpdates: (Int) -> String,
    val loadingHistory: String,
    val historyStart: String,
    val thoughtFor: (String) -> String,
    val thinking: String,
    val openFullOutput: String,
    val outputTruncated: String,
    val inputTruncated: String,
    val input: String,
    val output: String,
    val patchTruncated: String,
    val subtasks: (Int) -> String,
    val attachments: (Int) -> String,
    val running: String,
    val failed: String,
    val cancelled: String,
    /**
     * The caption above a message nobody here sent: typed at the keyboard, or
     * put into the conversation by another agent (A30).
     */
    val fromTerminal: String,
    val fromAgent: String,
    /** A35: the one message the device wrote for the person, and why. */
    val fromResume: String,
    val sending: String,
    val steering: String,
    val deliveryAbsorbed: String,
    val attachHintChannel: String,
    val attachHintDaemon: String,
    val attachHintExtension: String,
    val attachHintLeader: String,
    val attachHintRestart: String,
    val queuedRemove: String,
    val approvalNeeded: String,
    val approvalResolved: (String, String) -> String,
    val approvalElsewhere: String,
    val approvalExpired: String,
    val questionResolved: String,
    /** A20: the question was answered in the CLI's own dialog, not from here. */
    val questionAnsweredInTerminal: String,
    val questionExpired: String,
    val submitAnswer: String,
    val freeTextPlaceholder: String,
    val secretPlaceholder: String,
    val sessionErrored: String,
    val emptyTimeline: String,
    val turnInterrupted: String,
    val turnFailed: String,
    val copyCode: String,
    /**
     * A35 — a session the usage limit stopped, and the resume the device holds
     * for it (`docs/DESIGN.md` § "Paused by the usage limit"). The notice above
     * the transcript reads "Paused by the usage limit · resumes 3:50 PM", with
     * "about" when the device estimated the time and the try appended once a
     * resume has run into the limit again.
     */
    val pausedByLimit: String,
    val resumesAt: (String) -> String,
    val resumesAbout: (String) -> String,
    val resumeSecondTry: String,
    val resumeThirdTry: String,
    val resumeChange: String,
    val resumeCancel: String,
    val resumeAt: String,
    val resumeSet: String,
    val resumeTooSoon: String,
    val resumeTooFar: String,
    /** The device's own steps, as rows of the timeline in the notice voice. */
    val resumeScheduledAt: (String) -> String,
    val resumeScheduled: String,
    val resumeMovedTo: (String) -> String,
    val resumeMoved: String,
    val resumeCancelled: String,
    val resumeDropped: String,
    /** How a turn the vendor's usage limit ended closes. */
    val turnLimit: String,
    val turnLimitResets: (String) -> String,
) {
    companion object {
        val en = ChatStrings(
            newSession = "New session",
            searchPlaceholder = "Search",
            sidebarFooter = { devices, waiting -> "$devices ${if (devices == 1) "device" else "devices"} · $waiting waiting" },
            todos = { done, total -> "Todos $done/$total" },
            todosTitle = "Todos",
            stop = "Stop",
            stopping = "Stopping…",
            takeOver = "Take over",
            backToLatest = "Back to latest",
            newUpdates = { n -> "$n new" },
            loadingHistory = "Loading earlier messages…",
            historyStart = "Start of the conversation",
            thoughtFor = { s -> "Thought for $s" },
            thinking = "Thinking…",
            openFullOutput = "Open full output",
            outputTruncated = "output truncated",
            inputTruncated = "input truncated",
            input = "Input",
            output = "Output",
            patchTruncated = "patch truncated",
            subtasks = { n -> "$n ${if (n == 1) "step" else "steps"}" },
            attachments = { n -> "$n ${if (n == 1) "attachment" else "attachments"}" },
            running = "running",
            failed = "failed",
            cancelled = "cancelled",
            fromTerminal = "terminal",
            fromAgent = "from another agent",
            fromResume = "Sent for you after the limit reset",
            sending = "Sending…",
            steering = "the agent will read it at its next step",
            deliveryAbsorbed = "will be re-sent",
            attachHintChannel = "Start claude through the Remote Control shim to control it from here",
            attachHintDaemon = "Run rc-client codex setup on the device to attach its Codex sessions",
            attachHintExtension = "Run rc-client pi setup on the device to attach its pi sessions",
            attachHintLeader = "Run rc-client grok setup on the device, then restart Grok to attach its sessions",
            attachHintRestart = "This terminal session was started without the attachment; restart it to control it from here",
            queuedRemove = "Remove from queue",
            approvalNeeded = "Needs your approval",
            approvalResolved = { by, label -> "$label · decided by $by" },
            approvalElsewhere = "Answered in the terminal",
            approvalExpired = "This request expired.",
            questionResolved = "Answered",
            questionAnsweredInTerminal = "Answered in the terminal",
            questionExpired = "This question expired.",
            submitAnswer = "Submit",
            freeTextPlaceholder = "Type your answer…",
            secretPlaceholder = "Value is not stored or logged",
            sessionErrored = "The session reported an error.",
            emptyTimeline = "No messages yet. Say something to get started.",
            turnInterrupted = "Turn interrupted",
            turnFailed = "Turn failed",
            copyCode = "Copy code",
            pausedByLimit = "Paused by the usage limit",
            resumesAt = { `when` -> "resumes ${`when`}" },
            resumesAbout = { `when` -> "resumes about ${`when`}" },
            resumeSecondTry = "second try",
            resumeThirdTry = "third try",
            resumeChange = "Change",
            resumeCancel = "Cancel",
            resumeAt = "Resume at",
            resumeSet = "Set",
            resumeTooSoon = "Pick a time at least a minute from now.",
            resumeTooFar = "Pick a time within the next eight days.",
            resumeScheduledAt = { `when` -> "Resume scheduled for ${`when`}" },
            resumeScheduled = "Resume scheduled",
            resumeMovedTo = { `when` -> "Resume moved to ${`when`}" },
            resumeMoved = "Resume moved",
            resumeCancelled = "Resume cancelled",
            resumeDropped = "Not resumed",
            turnLimit = "Ended at the usage limit",
            turnLimitResets = { `when` -> "Ended at the usage limit · resets ${`when`}" },
        )

        val zhHans = ChatStrings(
            newSession = "新建会话",
            searchPlaceholder = "搜索",
            sidebarFooter = { devices, waiting -> "$devices 台设备 · $waiting 个等待" },
            todos = { done, total -> "待办 $done/$total" },
            todosTitle = "待办",
            stop = "停止",
            stopping = "停止中…",
            takeOver = "接管",
            backToLatest = "回到最新",
            newUpdates = { n -> "$n 条新消息" },
            loadingHistory = "加载更早的消息…",
            historyStart = "对话开始",
            thoughtFor = { s -> "思考了 $s" },
            thinking = "思考中…",
            openFullOutput = "查看完整输出",
            outputTruncated = "输出已截断",
            inputTruncated = "输入已截断",
            input = "输入",
            output = "输出",
            patchTruncated = "补丁已截断",
            subtasks = { n -> "$n 步" },
            attachments = { n -> "$n 个附件" },
            running = "运行中",
            failed = "失败",
            cancelled = "已取消",
            fromTerminal = "终端",
            fromAgent = "来自其他代理",
            fromResume = "限额恢复后代你发送",
            sending = "发送中…",
            steering = "agent 会在下一步读到它",
            deliveryAbsorbed = "将重新发送",
            attachHintChannel = "通过 Remote Control 垫片启动 claude，才能从这里控制它",
            attachHintDaemon = "在该设备上运行 rc-client codex setup，才能附着它的 Codex 会话",
            attachHintExtension = "在该设备上运行 rc-client pi setup，才能附着它的 pi 会话",
            attachHintLeader = "在该设备上运行 rc-client grok setup 并重启 Grok，才能附着它的会话",
            attachHintRestart = "这个终端会话启动时没有附着；重启它才能从这里控制",
            queuedRemove = "从队列中移除",
            approvalNeeded = "需要你的批准",
            approvalResolved = { by, label -> "$label · 由${by}决定" },
            approvalElsewhere = "已在终端回答",
            approvalExpired = "该请求已过期。",
            questionResolved = "已回答",
            questionAnsweredInTerminal = "已在终端回答",
            questionExpired = "该问题已过期。",
            submitAnswer = "提交",
            freeTextPlaceholder = "输入你的回答…",
            secretPlaceholder = "该值不会被保存或记录",
            sessionErrored = "会话报告了一个错误。",
            emptyTimeline = "还没有消息。说点什么开始吧。",
            turnInterrupted = "本轮已中断",
            turnFailed = "本轮失败",
            copyCode = "复制代码",
            pausedByLimit = "已因用量限额暂停",
            resumesAt = { `when` -> "将于 ${`when`} 继续" },
            resumesAbout = { `when` -> "约于 ${`when`} 继续" },
            resumeSecondTry = "第二次尝试",
            resumeThirdTry = "第三次尝试",
            resumeChange = "更改",
            resumeCancel = "取消",
            resumeAt = "继续时间",
            resumeSet = "设定",
            resumeTooSoon = "请选择至少一分钟之后的时间。",
            resumeTooFar = "请选择八天以内的时间。",
            resumeScheduledAt = { `when` -> "已安排于 ${`when`} 继续" },
            resumeScheduled = "已安排继续",
            resumeMovedTo = { `when` -> "继续时间改为 ${`when`}" },
            resumeMoved = "继续时间已更改",
            resumeCancelled = "已取消继续",
            resumeDropped = "未继续",
            turnLimit = "本轮因用量限额结束",
            turnLimitResets = { `when` -> "本轮因用量限额结束 · ${`when`} 恢复" },
        )

        /** The table an interface language reads. */
        fun of(language: InterfaceLanguage): ChatStrings = when (language) {
            InterfaceLanguage.en -> en
            InterfaceLanguage.zhHans -> zhHans
        }
    }
}
