/**
 * Simplified Chinese interface words. The English table in `strings.ts` is the
 * source and the type, so the compiler refuses this file the moment a key is
 * missing or renamed there.
 *
 * Only the app's own words live here. Everything the device reported — agent
 * output, device names, paths, branches, model, effort, permission and speed
 * labels — arrives translated by nobody and is drawn as it came. The product
 * name and every agent's name — "Claude Code", "Codex", "Grok Build" and "pi"
 * — stay as their makers write them, and each of the two interface languages is
 * always named in its own script.
 */
import type { StringTable } from './strings';

export const zhHans: StringTable = {
  productName: 'Remote Control',

  nav: {
    devices: '设备',
    sessions: '会话',
    settings: '设置',
    backToSessions: '返回会话',
    primary: '主导航',
  },

  common: {
    cancel: '取消',
    close: '关闭',
    continue: '继续',
    copy: '复制',
    copied: '已复制',
    retry: '重试',
    remove: '移除',
    save: '保存',
    rename: '重命名',
    revoke: '吊销',
    search: '搜索',
    loading: '加载中…',
    expand: '展开',
    collapse: '收起',
    showMore: '显示更多',
    showLess: '收起',
    dismiss: '忽略',
    unknown: '未知',
    none: '无',
    ok: '确定',
    done: '完成',
    of: '/',
  },

  account: {
    username: '用户名',
    password: '密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    role: '角色',
    rules: '用户名为 3 到 32 个字符：小写字母、数字、点、下划线和连字符。密码至少 8 个字符。',
    taken: '该用户名已被占用。',
    disabled: '该账户已被禁用。',
    wrongCurrentPassword: '当前密码不正确。',
    notAllowed: '该账户无法修改。',
    gone: '该账户已不存在。',
  },

  login: {
    title: 'Remote Control',
    subtitle: '登录后即可访问你的设备。',
    registerSubtitle: '在此网关上创建账户。',
    usernamePlaceholder: '用户名',
    passwordPlaceholder: '密码',
    submit: '登录',
    signingIn: '登录中…',
    createAccount: '创建账户',
    creating: '创建中…',
    createAccountLink: '创建账户',
    signInInstead: '返回登录',
    failed: '用户名或密码错误。',
    registrationClosed: '注册已关闭。',
    unreachable: '无法连接网关。',
    rateLimited: '尝试次数过多。请等待一分钟后重试。',
  },

  users: {
    title: '用户',
    registration: '开放注册',
    registrationCaption: '知道网关地址的人都可以创建账户',
    add: '添加用户',
    meta: (role: string, state: string) => `${role} · ${state}`,
    deviceCount: (n: number) => `${n} 台设备`,
    lastSignIn: (rel: string) => `上次登录 ${rel}`,
    never: '从未',
    resetPassword: '重设密码',
    resetPasswordTitle: (username: string) => `为 ${username} 重设密码`,
    disable: '禁用',
    enable: '启用',
    deleteAction: '删除',
    deleteTitle: '删除账户',
    deleteBody: (username: string) => `删除 ${username}？它的登录会立即失效，不保留任何内容。`,
    deleteBodyDevices: (username: string, n: number) =>
      `删除 ${username} 及其 ${n} 台设备？这些设备将被吊销，其会话会离开本网关。机器上的 agent 和记录不受影响。`,
    deleteConfirm: '删除账户',
    loadFailed: '无法加载账户列表。',
    registrationFailed: '无法修改该设置。',
  },

  devices: {
    title: '设备',
    subtitleCount: (online: number, total: number) => `已连接 ${online} · 共 ${total} 台设备`,
    empty: '还没有设备。',
    emptyHint: '添加安装了编程 agent 的机器。',
    add: '添加设备',
    sessionsCount: (n: number) => `${n} 个会话`,
    noSessions: '空闲',
    offline: '离线',
    lastSeen: (rel: string) => `最后在线 ${rel}`,
    renameTitle: '重命名设备',
    renameLabel: '设备名称',
    clientBuild: (version: string, build: string) => `客户端 ${version} · ${build}`,
    clientVersion: (version: string) => `客户端 ${version}`,
    retryUpdate: '重试更新',
    updating: '更新中…',
    updateFailed: (message: string) => `更新失败 · ${message}`,
    updateTitle: '更新设备',
    updateBody: (name: string, version: string | undefined) =>
      version === undefined
        ? `将 ${name} 更新到网关提供的客户端？它的服务会重启，由它驱动的会话会被停止。`
        : `将 ${name} 更新到 ${version}？它的服务会重启，由它驱动的会话会被停止。`,
    updateConfirm: '更新设备',
    updateOffline: '此设备当前离线。',
    updateNoBuild: '本网关未提供客户端安装包。',
    revokeTitle: '吊销设备',
    revokeBody: (name: string) =>
      `吊销 ${name}？它的令牌会失效，它的会话也会离开本网关。机器上的 agent 和记录都会保留。`,
    revokeConfirm: '吊销设备',
    noAgents: '未检测到 agent',
    online: '在线',
  },

  devicePage: {
    back: '设备',
    gone: '该设备已不在这里。',
    goneHint: '它已被吊销，或从未连接到本网关。',
    refresh: '刷新',
    accountOf: (vendor: string) => `${vendor} 账户`,
    apiKeyOf: (vendor: string) => `${vendor} API key`,
    notSignedIn: '未登录',
    checking: '检查中…',
    offlineQuota: '离线 · 无法获取配额',
    windowHours: (n: number) => `${n} 小时`,
    windowDays: (n: number) => `${n} 天`,
    windowMinutes: (n: number) => `${n} 分钟`,
    percent: (n: number) => `${n}%`,
    resets: (when: string) => `${when} 重置`,
    usage: (window: string) => `${window}用量`,
  },

  pairing: {
    title: '添加设备',
    intro: '在运行 agent 的机器上执行一条命令。它主动外连网关，主机不对外暴露任何端口。',
    singleUse: '一次性',
    expiresIn: (clock: string) => `${clock} 后过期`,
    expired: '已过期',
    newCode: '新配对码',
    waiting: '等待此设备',
    listening: (clock: string) => `监听中 ${clock}`,
    stepGateway: '网关就绪',
    stepHandshake: '设备握手',
    stepAgents: '检测已安装的 agent',
    connected: (name: string) => `${name} 已连接`,
    noCurl: '主机上没有 curl？',
    manualInstall: '手动安装',
    manualTitle: '手动安装',
    manualSteps: [
      '安装客户端：python3 -m pip install --user rc-client',
      '用下面的配对码与本网关配对。',
      '客户端在后台常驻，只主动外连。',
    ],
    manualPairCommand: (origin: string, code: string) =>
      `rc-client pair --gateway ${origin} --code ${code}`,
    createFailed: '无法创建配对码。',
    scanTitle: '从手机添加',
    scanBody: '主机会打印一个二维码。用手机 App 扫描它，或在这里打开它的链接。',
    scanCommand: (origin: string) => `curl -fsSL ${origin}/install.sh | sh`,
    claimTitle: '配对这台主机',
    claimIntro: '打印出这个码的主机正在加入你的网关。',
    claiming: '正在认领此码…',
    claimInvalid: '此链接不含配对码。',
    claimExpired: '此码已过期。请在主机上重新执行该命令。',
    claimUsed: '此码已被使用。',
    claimFailed: '无法认领此码。',
  },

  sessions: {
    title: '会话',
    new: '新建会话',
    searchPlaceholder: '搜索会话',
    empty: '还没有会话。',
    emptyHint: '从已配对的设备上新建一个，或在机器上打开一个终端会话。',
    noMatches: '没有匹配的结果。',
    allDevices: '全部设备',
    allAgents: '全部 agent',
    agentFilter: '按 agent 筛选',
    archive: '归档',
    archiveGroup: (n: number) => `归档 · ${n}`,
    archived: '已归档',
    open: '打开会话',
    untitled: '未命名会话',
    legend: '圆点含义',
    legendWorking: '运行中',
    legendAttention: '等你处理',
    legendOff: '未运行',
    legendFailed: '出错',
  },

  newSession: {
    title: '新建会话',
    continuingOn: (device: string) => `在 ${device} 上继续`,
    pickDevice: '选择要启动的设备',
    device: '设备',
    agent: 'Agent',
    agentUnavailable: '未安装',
    model: '模型',
    effort: '思考强度',
    permissions: '权限',
    speed: '速度',
    workingDirectory: '工作目录',
    browse: '浏览…',
    dirExists: '存在',
    dirMissing: '未找到',
    dirChecking: '检查中…',
    recent: '最近',
    git: 'Git',
    gitClean: '干净',
    gitDirty: '有未提交的改动',
    gitAhead: (n: number) => `领先 ${n}`,
    gitBehind: (n: number) => `落后 ${n}`,
    notARepo: '不是 git 仓库',
    isolateWorktree: '在 worktree 中隔离',
    start: '开始会话',
    starting: '启动中…',
    startFailed: '无法启动会话。',
    noDevices: '没有在线的设备。',
    browseTitle: '选择目录',
    browseUp: '上一级',
    browseUse: '使用此目录',
    browseEmpty: '没有子目录。',
  },

  chat: {
    newSession: '新建会话',
    searchPlaceholder: '搜索',
    sidebarFooter: (devices: number, waiting: number) => `${devices} 台设备 · ${waiting} 个等待`,
    todos: (done: number, total: number) => `待办 ${done}/${total}`,
    todosTitle: '待办',
    stop: '停止',
    stopping: '停止中…',
    takeOver: '接管',
    backToLatest: '回到最新',
    newUpdates: (n: number) => `${n} 条新消息`,
    loadingHistory: '加载更早的消息…',
    historyStart: '对话开始',
    thoughtFor: (s: string) => `思考了 ${s}`,
    thinking: '思考中…',
    openFullOutput: '查看完整输出',
    outputTruncated: '输出已截断',
    inputTruncated: '输入已截断',
    input: '输入',
    output: '输出',
    patchTruncated: '补丁已截断',
    subtasks: (n: number) => `${n} 步`,
    attachments: (n: number) => `${n} 个附件`,
    running: '运行中',
    failed: '失败',
    cancelled: '已取消',
    queuedLabel: '已排队',
    fromTerminal: '终端',
    fromAgent: '来自其他代理',
    fromResume: '限额恢复后代你发送',
    sending: '发送中…',
    steering: 'agent 会在下一步读到它',
    deliveryAbsorbed: '将重新发送',
    attachHintChannel: '通过 Remote Control 垫片启动 claude，才能从这里控制它',
    attachHintDaemon: '在该设备上运行 rc-client codex setup，才能附着它的 Codex 会话',
    attachHintExtension: '在该设备上运行 rc-client pi setup，才能附着它的 pi 会话',
    attachHintLeader: '在该设备上运行 rc-client grok setup 并重启 Grok，才能附着它的会话',
    attachHintRestart: '这个终端会话启动时没有附着；重启它才能从这里控制',
    queuedRemove: '从队列中移除',
    approvalNeeded: '需要你的批准',
    approvalResolved: (by: string, label: string) => `${label} · 由${by}决定`,
    approvalElsewhere: '已在终端回答',
    approvalExpired: '该请求已过期。',
    questionResolved: '已回答',
    questionAnsweredInTerminal: '已在终端回答',
    questionExpired: '该问题已过期。',
    submitAnswer: '提交',
    freeTextPlaceholder: '输入你的回答…',
    secretPlaceholder: '该值不会被保存或记录',
    sessionErrored: '会话报告了一个错误。',
    emptyTimeline: '还没有消息。说点什么开始吧。',
    turnInterrupted: '本轮已中断',
    turnFailed: '本轮失败',
    copyCode: '复制代码',

    pausedByLimit: '已因用量限额暂停',
    resumesAt: (when: string) => `将于 ${when} 继续`,
    resumesAbout: (when: string) => `约于 ${when} 继续`,
    resumeSecondTry: '第二次尝试',
    resumeThirdTry: '第三次尝试',
    resumeChange: '更改',
    resumeCancel: '取消',
    resumeAt: '继续时间',
    resumeSet: '设定',
    resumeTooSoon: '请选择至少一分钟之后的时间。',
    resumeTooFar: '请选择八天以内的时间。',
    resumeScheduledAt: (when: string) => `已安排于 ${when} 继续`,
    resumeScheduled: '已安排继续',
    resumeMovedTo: (when: string) => `继续时间改为 ${when}`,
    resumeMoved: '继续时间已更改',
    resumeCancelled: '已取消继续',
    resumeDropped: '未继续',
    turnLimit: '本轮因用量限额结束',
    turnLimitResets: (when: string) => `本轮因用量限额结束 · ${when} 恢复`,
  },

  status: {
    working: (agent: string) => `${agent} 正在工作`,
    workingQueued: (agent: string) => `${agent} 正在工作 · 消息将排队`,
    workingSteer: (agent: string) => `${agent} 正在工作 · 消息将转向当前任务`,
    needsApproval: '需要你的批准',
    needsInput: '等待你的回答',
    terminalControlled: '由终端控制',
    terminalBusy: '那边正在执行一轮任务',
    takeOverToSend: '接管后可发送',
    starting: '正在启动 agent…',
    stopped: '已停止',
    errored: '出错',
    idle: '空闲',
    offline: '设备离线',
  },

  composer: {
    placeholder: '给 agent 发消息…',
    placeholderQueued: '消息将排队…',
    placeholderSteer: '消息将转向当前任务…',
    placeholderTerminal: '由终端控制',
    placeholderOffline: '设备已离线',
    send: '发送',
    queue: '排队',
    answer: '回答',
    placeholderAnswer: '输入你的回答…',
    interruptAndSend: '中断并发送',
    sendOptions: '发送选项',
    attach: '添加附件',
    attachTooMany: (max: number) => `最多 ${max} 个附件。`,
    attachTooLarge: (name: string, max: string) => `${name} 超过 ${max}。`,
    attachFailed: (name: string) => `无法读取 ${name}。`,
    textTooLong: '消息过长（上限 64 KiB）。',
    deliveryUnconfirmed: '未确认送达',
    deliveryUnconfirmedBody: '网关没有确认你的上一条消息。',
    micStart: '开始语音输入',
    model: '模型',
    permissionMode: '权限模式',
    effort: '思考强度',
    modelCard: '模型与思考强度',
    speed: (tier: string) => `速度：${tier}`,
    speedStandard: '标准',
    option: (name: string, value: string) => `${name}：${value}`,
    setInTerminal: (name: string, value: string) => `${name} · ${value} · 在终端设置`,
    language: '语音语言',
    sendFailed: '无法发送消息。',
  },

  commands: {
    menu: '命令',
    rowLabel: (name: string, description: string) => `命令，/${name}，${description}`,
    whileRunning: '当前回合结束后可用',
    failed: '无法执行该命令。',
  },

  voice: {
    transcribing: '实时转写 · 发送前可编辑',
    connecting: '连接中…',
    done: '完成',
    finishing: '正在整理转写结果',
    listeningFor: (elapsed: string) => `已录制 ${elapsed}`,
    denied: '麦克风权限被拒绝。',
    unsupported: '此浏览器无法采集音频。',
    failed: '转写失败。',
    polishing: '润色中…',
    polished: '已润色',
    undo: '撤销',
    polishFailed: '润色失败，你的原话未改动',
  },

  settings: {
    title: '设置',
    account: '账户',
    signedInAs: '当前登录',
    changePassword: '修改密码',
    signOut: '退出登录',
    notifications: '通知',
    pushEnable: '推送通知',
    pushDescription: 'agent 需要你、或完成一轮任务时收到通知。',
    pushEnabled: '开',
    pushDisabled: '关',
    pushBlocked: '已在浏览器设置中被阻止',
    pushUnsupported: '此浏览器不支持推送通知。',
    pushServerDisabled: '网关未启用网页推送。',
    pushEnableAction: '开启',
    pushDisableAction: '关闭',
    sessions: '会话',
    resumeAfterLimit: '限额恢复后继续会话',
    resumeAfterLimitNote:
      'Claude Code 或 Codex 因用量限额停下时，设备会在限额恢复一分钟后继续该会话。',
    resumeUnavailable: '此网关尚不支持该功能。',
    voice: '语音',
    voiceLanguage: '默认语言',
    voiceServerDisabled: '此网关未配置语音转文字。',
    polish: '用 AI 润色口述',
    polishModel: '模型',
    polishStrength: '力度',
    polishModerate: '适中',
    polishStrong: '较强',
    polishChooseModel: '选择模型',
    polishNote:
      '开启后，你口述的内容与最近几条对话消息会发送到此网关配置的模型。关闭时不发送任何内容。',
    polishServerDisabled: '此网关未配置润色模型',
    polishModelsFailed: '无法加载模型列表。',
    language: '语言',
    timeline: '时间线',
    timelineDetail: '详细程度',
    timelineDetailNote: '简约只显示写给你的内容。详细会加上思考、工具调用和任务清单。',
    about: '关于',
    gatewayVersion: '网关版本',
    protocolVersion: '协议',
    origin: '网关地址',
    connection: '连接',
    connected: '已连接',
    connecting: '连接中…',
    offline: '离线',
  },

  connection: {
    reconnecting: '重新连接中…',
    offline: '连接已断开。正在重新连接…',
    restored: '已重新连接',
  },

  errors: {
    generic: '出了点问题。',
    stopFailed: '无法停止本轮任务。',
    approveFailed: '无法发送该决定。',
    answerFailed: '无法发送该回答。',
    expandFailed: '无法加载完整输出。',
    queueRemoveFailed: '无法移除排队的消息。',
    setFailed: '无法更改该设置。',
    takeoverFailed: '无法接管会话。',
    resumeSetFailed: '无法更改继续时间。',
    resumeCancelFailed: '无法取消继续。',
    notFound: '未找到。',
    sessionMissing: '该会话已不存在。',
    deviceOffline: '该设备已离线。',
    conflictTerminal: '该会话由终端控制。请先接管。',
    timeout: '设备未在规定时间内响应。',
    unsupported: '此设备不支持。',
    tooLarge: '负载过大。',
  },

  a11y: {
    statusDot: (state: string) => `状态：${state}`,
    openMenu: '打开菜单',
    closeDialog: '关闭对话框',
    toolRow: '工具调用',
    expandRow: '展开行',
    collapseRow: '收起行',
  },

  labels: {
    state: {
      starting: '启动中',
      idle: '空闲',
      running: '运行中',
      needs_approval: '待批准',
      needs_input: '待回答',
      error: '错误',
      stopped: '已停止',
      readonly: '终端',
    },
    dotTone: {
      working: '工作中',
      waiting: '等待你',
      live: '已完成',
      off: '未运行',
      failed: '出错',
    },
    voiceLanguage: {
      auto: '自动',
      zh: '中文',
      en: 'English',
      ja: '日本語',
      ko: '한국어',
      de: 'Deutsch',
      fr: 'Français',
      es: 'Español',
    },
    timelineDetail: { simple: '简约', detailed: '详细' },
    role: { admin: '管理员', member: '成员' },
    userState: { active: '正常', disabled: '已禁用' },
    origin: { terminal: '终端', remote: '远程启动' },
  },

  format: {
    dateLocale: 'zh-Hans',
    now: '刚刚',
    minutes: (n: number) => `${n} 分钟`,
    hours: (n: number) => `${n} 小时`,
    days: (n: number) => `${n} 天`,
    justNow: '刚刚',
    minutesAgo: (n: number) => `${n} 分钟前`,
    hoursAgo: (n: number) => `${n} 小时前`,
    yesterday: '昨天',
    daysAgo: (n: number) => `${n} 天前`,
    millis: (n: number) => `${n} 毫秒`,
    seconds: (s: string) => `${s} 秒`,
    minutesSeconds: (m: number, s: number) => `${m} 分 ${s} 秒`,
    hoursMinutes: (h: number, m: number) => `${h} 小时 ${m} 分`,
  },
};
