/**
 * Simplified Chinese interface words. The English table in `strings.ts` is the
 * source and the type, so the compiler refuses this file the moment a key is
 * missing or renamed there.
 *
 * Only the app's own words live here. Everything the device reported — agent
 * output, device names, paths, branches, model, effort, permission and speed
 * labels — arrives translated by nobody and is drawn as it came. The product
 * name, "Claude Code" and "Codex" stay in Latin script, and each of the two
 * interface languages is always named in its own script.
 */
import type { StringTable } from './strings';

export const zhHans: StringTable = {
  productName: 'Remote Control',

  nav: {
    devices: '设备',
    sessions: '会话',
    settings: '设置',
    backToSessions: '返回会话',
    primary: '主导航',
  },

  common: {
    cancel: '取消',
    close: '关闭',
    continue: '继续',
    copy: '复制',
    copied: '已复制',
    retry: '重试',
    remove: '移除',
    save: '保存',
    rename: '重命名',
    revoke: '吊销',
    search: '搜索',
    loading: '加载中…',
    expand: '展开',
    collapse: '收起',
    showMore: '显示更多',
    showLess: '收起',
    dismiss: '忽略',
    unknown: '未知',
    none: '无',
    ok: '确定',
    done: '完成',
    of: '/',
  },

  login: {
    title: 'Remote Control',
    subtitle: '登录后即可访问你的设备。',
    password: '网关密码',
    passwordPlaceholder: '密码',
    submit: '登录',
    signingIn: '登录中…',
    failed: '密码错误。',
    unreachable: '无法连接网关。',
    rateLimited: '尝试次数过多。请等待一分钟后重试。',
  },

  devices: {
    title: '设备',
    subtitleCount: (online: number, total: number) => `已连接 ${online} · 共 ${total} 台设备`,
    empty: '还没有设备。',
    emptyHint: '添加安装了 Claude Code 或 Codex 的机器。',
    add: '添加设备',
    sessionsCount: (n: number) => `${n} 个会话`,
    noSessions: '空闲',
    offline: '离线',
    lastSeen: (rel: string) => `最后在线 ${rel}`,
    renameTitle: '重命名设备',
    renameLabel: '设备名称',
    clientBuild: (version: string, build: string) => `客户端 ${version} · ${build}`,
    clientVersion: (version: string) => `客户端 ${version}`,
    update: '更新',
    updateAvailable: '有可用更新',
    updating: '更新中…',
    updateFailed: (message: string) => `更新失败 · ${message}`,
    updateTitle: '更新设备',
    updateBody: (name: string) =>
      `将 ${name} 更新到网关提供的客户端？它的服务会重启，由它驱动的会话会被停止。`,
    updateConfirm: '更新设备',
    updateOffline: '此设备当前离线。',
    updateInFlight: '此设备正在更新。',
    updateCurrent: '此设备已在运行网关提供的版本。',
    updateNoBuild: '本网关未提供客户端安装包。',
    revokeTitle: '吊销设备',
    revokeBody: (name: string) =>
      `吊销 ${name}？它的令牌会失效，它的会话也会离开本网关。机器上的 agent 和记录都会保留。`,
    revokeConfirm: '吊销设备',
    noAgents: '未检测到 agent',
  },

  pairing: {
    title: '添加设备',
    intro: '在运行 agent 的机器上执行一条命令。它主动外连网关，主机不对外暴露任何端口。',
    macos: 'macOS',
    linux: 'Linux',
    singleUse: '一次性',
    expiresIn: (clock: string) => `${clock} 后过期`,
    expired: '已过期',
    newCode: '新配对码',
    waiting: '等待此设备',
    listening: (clock: string) => `监听中 ${clock}`,
    stepGateway: '网关就绪',
    stepHandshake: '设备握手',
    stepAgents: '检测已安装的 agent',
    connected: (name: string) => `${name} 已连接`,
    noCurl: '主机上没有 curl？',
    manualInstall: '手动安装',
    manualTitle: '手动安装',
    manualSteps: [
      '安装客户端：python3 -m pip install --user rc-client',
      '用下面的配对码与本网关配对。',
      '客户端在后台常驻，只主动外连。',
    ],
    manualPairCommand: (origin: string, code: string) =>
      `rc-client pair --gateway ${origin} --code ${code}`,
    createFailed: '无法创建配对码。',
    scanTitle: '从手机添加',
    scanBody: '主机会打印一个二维码。用手机 App 扫描它，或在这里打开它的链接。',
    scanCommand: (origin: string) => `curl -fsSL ${origin}/install.sh | sh`,
    claimTitle: '配对这台主机',
    claimIntro: '打印出这个码的主机正在加入你的网关。',
    claiming: '正在认领此码…',
    claimInvalid: '此链接不含配对码。',
    claimExpired: '此码已过期。请在主机上重新执行该命令。',
    claimUsed: '此码已被使用。',
    claimFailed: '无法认领此码。',
  },

  sessions: {
    title: '会话',
    new: '新建会话',
    searchPlaceholder: '搜索会话',
    empty: '还没有会话。',
    emptyHint: '从已配对的设备上新建一个，或在机器上打开一个终端会话。',
    noMatches: '没有匹配的结果。',
    allDevices: '全部设备',
    allAgents: '全部',
    agentFilter: '按 agent 筛选',
    archive: '归档',
    archiveGroup: (n: number) => `归档 · ${n}`,
    archived: '已归档',
    deviceOffline: '设备离线',
    open: '打开会话',
    untitled: '未命名会话',
  },

  newSession: {
    title: '新建会话',
    continuingOn: (device: string) => `在 ${device} 上继续`,
    pickDevice: '选择要启动的设备',
    device: '设备',
    agent: 'Agent',
    agentUnavailable: '未安装',
    model: '模型',
    effort: '思考强度',
    permissions: '权限',
    speed: '速度',
    workingDirectory: '工作目录',
    browse: '浏览…',
    dirExists: '存在',
    dirMissing: '未找到',
    dirChecking: '检查中…',
    recent: '最近',
    git: 'Git',
    gitClean: '干净',
    gitDirty: '有未提交的改动',
    gitAhead: (n: number) => `领先 ${n}`,
    gitBehind: (n: number) => `落后 ${n}`,
    notARepo: '不是 git 仓库',
    isolateWorktree: '在 worktree 中隔离',
    start: '开始会话',
    starting: '启动中…',
    startFailed: '无法启动会话。',
    noDevices: '没有在线的设备。',
    browseTitle: '选择目录',
    browseUp: '上一级',
    browseUse: '使用此目录',
    browseEmpty: '没有子目录。',
  },

  chat: {
    newSession: '新建会话',
    searchPlaceholder: '搜索',
    sidebarFooter: (devices: number, waiting: number) => `${devices} 台设备 · ${waiting} 个等待`,
    todos: (done: number, total: number) => `待办 ${done}/${total}`,
    todosTitle: '待办',
    stop: '停止',
    stopping: '停止中…',
    takeOver: '接管',
    backToLatest: '回到最新',
    newUpdates: (n: number) => `${n} 条新消息`,
    loadingHistory: '加载更早的消息…',
    historyStart: '对话开始',
    thoughtFor: (s: string) => `思考了 ${s}`,
    thinking: '思考中…',
    openFullOutput: '查看完整输出',
    outputTruncated: '输出已截断',
    inputTruncated: '输入已截断',
    input: '输入',
    output: '输出',
    patchTruncated: '补丁已截断',
    subtasks: (n: number) => `${n} 步`,
    attachments: (n: number) => `${n} 个附件`,
    running: '运行中',
    failed: '失败',
    cancelled: '已取消',
    queuedLabel: '已排队',
    sending: '发送中…',
    steering: 'agent 会在下一步读到它',
    deliveryAbsorbed: '将重新发送',
    attachHintChannel: '通过 Remote Control 垫片启动 claude，才能从这里控制它',
    attachHintDaemon: '在此设备上启动 Codex app-server 守护进程，才能从这里控制它',
    attachHintRestart: '这个终端会话启动时没有附着；重启它才能从这里控制',
    queuedRemove: '从队列中移除',
    approvalNeeded: '需要你的批准',
    approvalResolved: (by: string, label: string) => `${label} · 由${by}决定`,
    approvalElsewhere: '已在终端回答',
    approvalExpired: '该请求已过期。',
    questionResolved: '已回答',
    questionAnsweredInTerminal: '已在终端回答',
    questionExpired: '该问题已过期。',
    submitAnswer: '提交',
    freeTextPlaceholder: '输入你的回答…',
    secretPlaceholder: '该值不会被保存或记录',
    sessionErrored: '会话报告了一个错误。',
    emptyTimeline: '还没有消息。说点什么开始吧。',
    turnInterrupted: '本轮已中断',
    turnFailed: '本轮失败',
    copyCode: '复制代码',
  },

  status: {
    working: (agent: string) => `${agent} 正在工作`,
    workingQueued: (agent: string) => `${agent} 正在工作 · 消息将排队`,
    workingSteer: (agent: string) => `${agent} 正在工作 · 消息将转向当前任务`,
    needsApproval: '需要你的批准',
    needsInput: '等待你的回答',
    terminalControlled: '由终端控制',
    terminalBusy: '那边正在执行一轮任务',
    starting: '正在启动 agent…',
    stopped: '已停止',
    errored: '出错',
    idle: '空闲',
    offline: '设备离线',
  },

  composer: {
    placeholder: '给 agent 发消息…',
    placeholderQueued: '消息将排队…',
    placeholderSteer: '消息将转向当前任务…',
    placeholderTerminal: '由终端控制 · 接管后可发送',
    placeholderOffline: '设备已离线',
    send: '发送',
    queue: '排队',
    answer: '回答',
    placeholderAnswer: '输入你的回答…',
    interruptAndSend: '中断并发送',
    sendOptions: '发送选项',
    attach: '添加附件',
    attachTooMany: (max: number) => `最多 ${max} 个附件。`,
    attachTooLarge: (name: string, max: string) => `${name} 超过 ${max}。`,
    attachFailed: (name: string) => `无法读取 ${name}。`,
    textTooLong: '消息过长（上限 64 KiB）。',
    deliveryUnconfirmed: '未确认送达',
    deliveryUnconfirmedBody: '网关没有确认你的上一条消息。',
    micStart: '开始语音输入',
    model: '模型',
    permissionMode: '权限模式',
    effort: '思考强度',
    modelCard: '模型与思考强度',
    speed: (tier: string) => `速度：${tier}`,
    speedStandard: '标准',
    option: (name: string, value: string) => `${name}：${value}`,
    setInTerminal: (name: string, value: string) => `${name} · ${value} · 在终端设置`,
    language: '语音语言',
    sendFailed: '无法发送消息。',
  },

  voice: {
    transcribing: '实时转写 · 发送前可编辑',
    connecting: '连接中…',
    done: '完成',
    listeningFor: (elapsed: string) => `已录制 ${elapsed}`,
    denied: '麦克风权限被拒绝。',
    unsupported: '此浏览器无法采集音频。',
    failed: '转写失败。',
  },

  settings: {
    title: '设置',
    account: '账户',
    signedInAs: '当前登录',
    signOut: '退出登录',
    notifications: '通知',
    pushEnable: '推送通知',
    pushDescription: 'agent 需要你、或完成一轮任务时收到通知。',
    pushEnabled: '开',
    pushDisabled: '关',
    pushBlocked: '已在浏览器设置中被阻止',
    pushUnsupported: '此浏览器不支持推送通知。',
    pushServerDisabled: '网关未启用网页推送。',
    pushEnableAction: '开启',
    pushDisableAction: '关闭',
    voice: '语音',
    voiceLanguage: '默认语言',
    voiceServerDisabled: '此网关未配置语音转文字。',
    language: '语言',
    timeline: '时间线',
    timelineDetail: '详细程度',
    timelineDetailNote: '简约只显示写给你的内容。详细会加上思考、工具调用和任务清单。',
    about: '关于',
    gatewayVersion: '网关版本',
    protocolVersion: '协议',
    origin: '网关地址',
    connection: '连接',
    connected: '已连接',
    connecting: '连接中…',
    offline: '离线',
  },

  connection: {
    reconnecting: '重新连接中…',
    offline: '连接已断开。正在重新连接…',
    restored: '已重新连接',
  },

  errors: {
    generic: '出了点问题。',
    stopFailed: '无法停止本轮任务。',
    approveFailed: '无法发送该决定。',
    answerFailed: '无法发送该回答。',
    expandFailed: '无法加载完整输出。',
    queueRemoveFailed: '无法移除排队的消息。',
    setFailed: '无法更改该设置。',
    takeoverFailed: '无法接管会话。',
    notFound: '未找到。',
    sessionMissing: '该会话已不存在。',
    deviceOffline: '该设备已离线。',
    conflictTerminal: '该会话由终端控制。请先接管。',
    timeout: '设备未在规定时间内响应。',
    unsupported: '此设备不支持。',
    tooLarge: '负载过大。',
  },

  a11y: {
    statusDot: (state: string) => `状态：${state}`,
    openMenu: '打开菜单',
    closeDialog: '关闭对话框',
    toolRow: '工具调用',
    expandRow: '展开行',
    collapseRow: '收起行',
  },

  labels: {
    state: {
      starting: '启动中',
      idle: '空闲',
      running: '运行中',
      needs_approval: '待批准',
      needs_input: '待回答',
      error: '错误',
      stopped: '已停止',
      readonly: '终端',
    },
    dotTone: {
      working: '工作中',
      waiting: '等待你',
      live: '实时',
      off: '关闭',
      failed: '失败',
    },
    voiceLanguage: {
      auto: '自动',
      zh: '中文',
      en: 'English',
      ja: '日本語',
      ko: '한국어',
      de: 'Deutsch',
      fr: 'Français',
      es: 'Español',
    },
    timelineDetail: { simple: '简约', detailed: '详细' },
    terminal: '终端',
    terminalAttached: '终端 · 已连接',
    terminalBusy: (state: string) => `终端 · ${state}`,
  },

  format: {
    dateLocale: 'zh-Hans',
    now: '刚刚',
    minutes: (n: number) => `${n} 分钟`,
    hours: (n: number) => `${n} 小时`,
    days: (n: number) => `${n} 天`,
    justNow: '刚刚',
    minutesAgo: (n: number) => `${n} 分钟前`,
    hoursAgo: (n: number) => `${n} 小时前`,
    yesterday: '昨天',
    daysAgo: (n: number) => `${n} 天前`,
    millis: (n: number) => `${n} 毫秒`,
    seconds: (s: string) => `${s} 秒`,
    minutesSeconds: (m: number, s: number) => `${m} 分 ${s} 秒`,
    hoursMinutes: (h: number, m: number) => `${h} 小时 ${m} 分`,
  },
};
